spring.application.name=demo

# BASE DE DATOS MS SQL SERVER

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GestionEnfermedades_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=localhost
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#CONFIG DE Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#CONFIG ThymeLeaf
spring.thymeleaf.cache=false

#CONFIG SMTP PARA JavaMail CON Spring
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nganaj@unicartagena.edu.co
spring.mail.password=ardt aase qqsr iigf
spring.mail.from.address=nganaj@unicartagena.edu.co
spring.mail.from.name=Gestion de Enfermedades
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true