spring.application.name=demo

# BASE DE DATOS MS SQL SERVER

spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#CONFIG DE Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#CONFIG ThymeLeaf
spring.thymeleaf.cache=false

#CONFIG SMTP PARA JavaMail CON Spring
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nganaj@unicartagena.edu.co
spring.mail.password=ardt aase qqsr iigf
spring.mail.from.address=nganaj@unicartagena.edu.co
spring.mail.from.name=Gestion de Enfermedades
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true